### PR TITLE
Rc/1.7.0

### PR DESCRIPTION
**Pull request by valentunn**
Staking is here

### CODE REVIEW

**Comment by valentunn** [comment]
Do not merge!

**Review by antonkhvorov — APPROVED** [review]
Staking lets go 🎉

**Review by antonkhvorov — CHANGES_REQUESTED** [review]
RC PR, not merging

**Comment by valentunn** [comment]
RC is Published, ready to merge

**Review by antonkhvorov — APPROVED** [review]
🎉🎉🎉

**Pull request merged**
