### PR TITLE
Feature/tap zone

### PR DESCRIPTION
**Pull request by FrogTravel**
Tap zone for the whole stake view except of status

### CODE REVIEW

**Comment by valentunn** [comment]
Can you provide an example of how it looks after changes?

**Comment by FrogTravel** [comment]
> Can you provide an example of how it looks after changes?

UI didn't change, but now you can tap on the whole widget to open Bottom Sheet. Before you had to click on "more "kebab" icon"

**Comment by valentunn** [comment]
> > Can you provide an example of how it looks after changes?
> 
> UI didn't change, but now you can tap on the whole widget to open Bottom Sheet. Before you had to click on "more "kebab" icon"

I mean, how the tapzone looks after changes?

**Comment by FrogTravel** [comment]
> > > Can you provide an example of how it looks after changes?
> > 
> > 
> > UI didn't change, but now you can tap on the whole widget to open Bottom Sheet. Before you had to click on "more "kebab" icon"
> 
> I mean, how the tapzone looks after changes?

You can click on all stake widget except of status part to open the BottomSheet

**Review by valentunn — APPROVED** [review]

**Pull request merged**
