### PR TITLE
Changed api tokens

### PR DESCRIPTION
**Pull request by FrogTravel**
Changed Api tokens in onFinality to the new one for polkadot and kusama

### CODE REVIEW

**Comment by antonkhvorov** [comment]
@FrogTravel Will it passes the migration, e.g. if the user already using the OnFinality node, and updates the app with this one - will URL on his current connection change? I would double-check that

**Comment by valentunn** [comment]
@antonkhvorov you're right, miration is required to affect existing devices
@FrogTravel  please use UpdateDefaultNodesList migration

**Review by valentunn — CHANGES_REQUESTED** [review]
Needs migration

**Comment by FrogTravel** [comment]
> Needs migration

Done

**Review by valentunn — APPROVED** [review]

**Pull request merged**
