### PR TITLE
Update linter to match Kotlin version (1.4.21)

### PR DESCRIPTION
**Pull request by izhestkov**

### CODE REVIEW

**Comment by valentunn** [comment]
Thanks for your contribution! Is it possible to update linter without breaking existing formatting? There some really weird formattings like this one:
``` kotlin
 validatorIdentityBody.setCompoundDrawablesWithIntrinsicBounds(
                0,
                0,
                0,
                0
            )
```
So probably it would be better to adjust linter settings to the one that is currently used. Thanks

**Comment by valentunn** [comment]
Resolves #189

**Comment by valentunn** [comment]
Resolves #149

**Comment by izhestkov** [comment]
> Thanks for your contribution! Is it possible to update linter without breaking existing formatting? There some really weird formattings like this one:
> 
> ```kotlin
>  validatorIdentityBody.setCompoundDrawablesWithIntrinsicBounds(
>                 0,
>                 0,
>                 0,
>                 0
>             )
> ```
> 
> So probably it would be better to adjust linter settings to the one that is currently used. Thanks



> Thanks for your contribution! Is it possible to update linter without breaking existing formatting? There some really weird formattings like this one:
> 
> ```kotlin
>  validatorIdentityBody.setCompoundDrawablesWithIntrinsicBounds(
>                 0,
>                 0,
>                 0,
>                 0
>             )
> ```
> 
> So probably it would be better to adjust linter settings to the one that is currently used. Thanks

**Comment by izhestkov** [comment]
The new ktlint version contains a rule for the maximum line length [max_line_length], by default it is 100. It is impossible to disable it in the ktlint configuration, so I increased it to 120 to reduce the number of files to format)

**Comment by ArtemNeFRiT** [comment]
> The new ktlint version contains a rule for the maximum line length [max_line_length], by default it is 100. It is impossible to disable it in the ktlint configuration, so I increased it to 120 to reduce the number of files to format)

I think we can increase this number to 160-180 for now to not block other changes without formatting current lines

**Comment by izhestkov** [comment]
> > The new ktlint version contains a rule for the maximum line length [max_line_length], by default it is 100. It is impossible to disable it in the ktlint configuration, so I increased it to 120 to reduce the number of files to format)
> 
> I think we can increase this number to 160-180 for now to not block other changes without formatting current lines

done!

**Review by valentunn — APPROVED** [review]

**Review by ArtemNeFRiT — APPROVED** [review]

**Pull request merged**
